# Generated by Django 6.0.5 on 2026-05-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transfers.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender_wallet', to='transfers.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receiver_wallet', to='transfers.wallet'),
        ),
        migrations.CreateModel(
            name='LedgerEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit')], max_length=6)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transfers.transaction')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transfers.wallet')),
            ],
        ),
    ]
